services:
  - type: web
    name: ark-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: RPC_URL
        value: https://bsc-mainnet.nodereal.io/v1/d96a4e697b0541628f61ae6089a97874
