services:
  - type: web
    name: ark-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
